### PR TITLE
Fix: show newly created board on homepage without reload

### LINKED ISSUE #42: The page must be reloaded in order to view the newly created board
**Describe the bug**
When a new board is created, it redirects to its page. However, when we go back to the main page, the new board does not appear until we reload the page.

**To Reproduce**

1. Go to Create board
2. Create board
3. Go to main page (where is list of boards)

**Expected behavior**
Created board should be on the list

**Screenshots**
https://github.com/0l1v3rr/trello-clone/assets/60447475/38605d58-aa3a-4edc-96c9-1a2ea799bf0e

### PR DESCRIPTION
**Pull request by sanjaykumaryada**
## Description

Fixes #42 : Issue was that newly created board was not getting updated without reload. To resolve this I created a context for the list of created boards and updated the state accordingly.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style and structure of this project
- [x] My code follows the principles of clean code
- [x] My changes generate no new warnings, bugs or errors

## Tags

`hactoberfest`, `bug-fix`, `hactoberfest2023`

### CODE REVIEW

File: src/app/(dashboard)/_components/boards/board-list.tsx [hunk 1]
```diff
@@ -10,14 +10,12 @@ interface BoardListProps {
...
-  boards,
+  boards = [],
   showCreateBoardBtn = false,
 }) => {
   return (
     <div className="grid grid-cols-2 gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
-      {boards.map((board) => (
-        <BoardItem key={board.id} board={board} />
-      ))}
+      {boards?.map((board) => <BoardItem key={board.id} board={board} />)}
```
Comment (0l1v3rr) [inline src/app/(dashboard)/_components/boards/board-list.tsx:18]:
```suggestion
      {boards.map((board) => <BoardItem key={board.id} board={board} />)}
```

File: src/app/(dashboard)/_components/boards/boards.tsx [hunk 2]
```diff
@@ -1,26 +1,23 @@
...
-import { options } from "@/app/api/auth/[...nextauth]/options";
 
 interface BoardsProps {
   className?: string;
 }
 
-const Boards: FC<BoardsProps> = async ({ className }) => {
-  const session = await getServerSession(options);
+const Boards: FC<BoardsProps> = ({ className }) => {
+  const { boardList, guestBoards, session } = useContext(BoardListContext);
```
Comment (0l1v3rr) [inline src/app/(dashboard)/_components/boards/boards.tsx:14]: Please use the custom hook you created in the board-list-context

File: src/context/boardList-context.tsx
Comment (0l1v3rr) [inline src/context/boardList-context.tsx:1]: Rename this file to `board-list-context` or something similar. With `boardList-context`, you use camel case and kebab case at the same time.

File: src/context/boardList-context.tsx [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+  useContext,
+  useState,
+} from "react";
+import { type Session } from "next-auth";
+import { BoardWithOwner } from "@/components/navbar/dropdowns/boards-dropdown";
+
+interface BoardListContextProps {
+  boardList: BoardWithOwner[];
+  guestBoards: BoardWithOwner[];
+  setBoardList: React.Dispatch<React.SetStateAction<BoardWithOwner[]>>;
```
Comment (0l1v3rr) [inline src/context/boardList-context.tsx:16]:
```suggestion
  setBoardList: (boards: BoardWithOwner[]) => void;
```

File: src/context/boardList-context.tsx [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+  session: Session | null;
+  setGuestBoard: React.Dispatch<React.SetStateAction<BoardWithOwner[]>>;
```
Comment (0l1v3rr) [inline src/context/boardList-context.tsx:18]: Do the same as above

**Review by 0l1v3rr — CHANGES_REQUESTED** [review]

**Comment by 0l1v3rr** [comment]
Hello @sanjaykumaryada, thanks!
